### ISSUE TITLE
Basic Auth not working with browsers

### ISSUE THREAD

**Issue by flo-assling** [jthomperoo/simple-proxy#1]
Thank you for providing this script.
Works perfectly without authentication.
But when starting with basic auth, and adding the correct credentials to my browser, I always get "Unauthorized"...
Tested starting with with --basic-auth 'user:pass' // --basic-auth user:pass // -basic-auth 'user:pass' // -basic-auth user:pass

**Comment by kanwairen123** [comment]
It seems the browser not sending the "Proxy-Authorization" header to proxy server, I'm also struggling with the issue, if you have a solution, kindly share with me, thank you!

**Comment by jthomperoo** [comment]
Sorry for such a slow fix on this.

Thanks @kanwairen123 you were right and started me in the right direction - digging into the Chrome spec this proxy was using the wrong responses. For HTTP auth to work with browsers they need to not respond with a `401 Unauthorized` on authorization failure, but instead a `407 Proxy Authentication Required`, and to return the `Proxy-Authenticate` header with the authorization type (`Basic` for this proxy).

Read more about it here:
https://www.chromium.org/spdy/spdy-authentication/#proxy-authentication

I've put a fix together in this pull request: #3 

Just going to do some sanity testing around this and I'll merge + cut a new version.

The behaviour will be this:

1. Set up your proxy, for my Mac it is done through system settings for Chrome.
2. When I load a site on Chrome it will prompt me for the authentication details.
3. When I put those in the authentication works for me.

**Comment by jthomperoo** [comment]
Available with version [`v1.1.1`](https://github.com/jthomperoo/simple-proxy/releases/tag/v1.1.1), let me know if this solves it for you :)

**Comment by kanwairen123** [comment]
> Available with version [`v1.1.1`](https://github.com/jthomperoo/simple-proxy/releases/tag/v1.1.1), let me know if this solves it for you :)

Thanks, works as expected now!
