### ISSUE TITLE
Arg to specify bind IP

### ISSUE THREAD

**Issue by fiddyschmitt** [jthomperoo/simple-proxy#6]
Hi Jamie,

Thanks for simple-proxy!

Could you please add an arg which lets me specify the IP to bind to?

eg.

`--bind 127.0.0.1 --port 8888`

Currently simple-proxy seems to bind to 0.0.0.0 (all interfaces), which on some machines requires admin rights (whereas binding to 127.0.0.1 does not).

Thanks!
Fidel

**Comment by jthomperoo** [comment]
Hi Fidel!

That seems like a good feature, I've put together the changes for that now, I'll get a new version cut which will be `v1.2.0` which will have this in it.

Thanks!

**Comment by jthomperoo** [comment]
This is now available in [`v1.2.0`](https://github.com/jthomperoo/simple-proxy/releases/tag/v1.2.0), thanks for raising the issue!

**Comment by fiddyschmitt** [comment]
Amazing turnaround time!! Thanks so much!
